### ISSUE TITLE
Batch and interval arguments are confusing

### ISSUE THREAD

**Issue by jake2184** [benhoyt/graphyte#14]
Hi,

I've been digging into the code and tweaking behaviour as the module wasn't working for me with large metric counts.

My assumption reading the documentation, and standard queuing behaviour, would be that batch size and interval are to ensure steady throughput to a graphite server. However that doesn't seem to be the case. The batch size works in that is how many metrics are sent in one socket operation, but there is no delay based on the interval.

For instance:
- Create an async sender queue with batch size 50, and interval 5
- Put 1000 metrics onto the queue
- I would now expect the lib to send 50 metrics, every 5 seconds, so 1200 message a minute.
- Instead, I can log graphyte sending 50 messages to the socket at a time, without a delay
```
2021-07-20 13:22:15,309 - graphite-buffer - INFO - sent message of 6185B, 50 metrics, to graphite:2003 in 0.222 seconds
2021-07-20 13:22:15,536 - graphite-buffer - INFO - sent message of 6204B, 50 metrics, to graphite:2003 in 0.227 seconds
2021-07-20 13:22:15,762 - graphite-buffer - INFO - sent message of 6173B, 50 metrics, to graphite:2003 in 0.226 seconds
2021-07-20 13:22:15,985 - graphite-buffer - INFO - sent message of 6206B, 50 metrics, to graphite:2003 in 0.223 seconds
2021-07-20 13:22:16,211 - graphite-buffer - INFO - sent message of 6205B, 50 metrics, to graphite:2003 in 0.225 seconds
```

The guilty code being:
```
                if current_time - last_check_time >= self.interval:
                    last_check_time = current_time
                    for i in range(0, len(messages), self.batch_size):
                       batch = messages[i:i + self.batch_size]
                       self.send_socket(b''.join(batch))
                    messages = []
```
It seems the algorithm is to check the queue every `interval` seconds, then flush the entire queue with `batch` number of metrics in each write operation?

So, is this behaviour intentional, and `interval` is how often the thread queue basically wakes up and flushes the queue? Or is this buggy behaviour, and it should instead read&send a specific number of metrics (batch #) off the queue each interval?

**Comment by benhoyt** [comment]
Hi @jake2184, it's been a while since I wrote this code, but yeah, this is intentional. The idea is that the thread wakes up *at least* every `interval` seconds if you're sending slowly, but it'll happily send faster than that if the caller is adding metrics faster. So the `interval` is to specify the maximum time between sends when sending fairly slowly; it's not intended for throttling.

I realize now that the docs/README don't make this particularly clear -- I'd happily accept a PR to clear this up in the README and/or code comments.

**Comment by jake2184** [comment]
Ok - if it's intentional that's not a problem, I'll likely just end up forking the code base - I'm using this to write a daemon to collect tens of 1000s of metrics, dumped once a minute, and slowly stream data up to a central server.

Thanks for the quick response.
