### ISSUE TITLE
add support for a statsd styled message

### ISSUE THREAD

**Issue by delphid** [benhoyt/graphyte#16]
Hi, benhoyt, just be utilizing this awesome package for sending metrics to a statsite server. And did some customization in order to comply with the [statsite](https://github.com/statsite/statsite#protocol)/ [statsd](https://github.com/statsd/statsd#usage) protocol.
- the default graphite protocol: {metric} {value} {timestamp}
- the statsd styled protocol: {metric}:{value}|{type}

Just in case if anyone else would need this feature, would you like to check out this modification:
[the forked branch](https://github.com/delphid/graphyte/tree/statsd_message_style)

**Comment by benhoyt** [comment]
Nice, thank you for the link! I don't think I'll include this in graphyte itself, but maybe I can link to your branch in the README.

**Comment by delphid** [comment]
Yes, nice consideration. Thank you.

**Comment by benhoyt** [comment]
I've added a link to your work to the bottom of the README now. Thanks!
