### ISSUE TITLE
distutils is deprecated in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [benhoyt/graphyte#19]
Ref : https://www.python.org/dev/peps/pep-0632/#migration-advice

`setup` from setuptools can be used.

https://github.com/benhoyt/graphyte/blob/db0c0f43cdb4380448e7a5da81b371f52e979101/setup.py#L6

**Comment by benhoyt** [comment]
Fixed, and I uploaded version 1.7.1 including this to PyPI: https://pypi.org/project/graphyte/

**Comment by benhoyt** [comment]
Thanks for the report!
