### ISSUE TITLE
rounding timestamp will loose some data

### ISSUE THREAD

**Issue by knvpk** [benhoyt/graphyte#4]
Hi, you are actually rounding timestamp if so then some of the millisecond data will be loosed. Actually you need to send timestamp as it is to stasd.

**Comment by benhoyt** [comment]
Hmmm, I'm not sure:

1. This [Graphite doc page, see "timestamp"](http://graphite.readthedocs.io/en/latest/terminology.html#term-timestamp) suggests that the resolution is one second.
2. In the [Protocol Buffers protocol](https://github.com/graphite-project/carbon/blob/f2680aa970e36f4012e3149e273407470f32ee9d/lib/carbon/carbon.proto#L7) the timestamp is defined as a uint32, i.e., an integer number of seconds.
3. There's also the `MIN_TIMESTAMP_RESOLUTION` setting that truncates it even further, for example to a resolution of 10 seconds.
4. But if that setting is not set, the [Graphite code](https://github.com/graphite-project/carbon/blob/7516cf148c5d75c2cd066c32ad95f5d617cca2f0/lib/carbon/protocols.py#L194) converts the timestamp using `float()`.

Bullet number 4 above would indicate you're right, but bullets 1-3 indicate it's intended to be an integer number of seconds.

Additionally, the Go version of Carbon stores timestamps as integer number of seconds too.

So I'm inclined to leave this as is, as I think that's the intent of the documentation and Graphite "standard".

**Comment by velantan92** [comment]
Past Date not getting added to graphite
where am i going wrong? The format is the same at the end.

#Does not work
val = datetime.strptime(strDatetime, '%m-%d-%Y %H:%M:%S').timestamp() + 0.1111111

#works
val = datetime.now().timestamp() + 0.0000011
