### ISSUE TITLE
Data not getting added when given past datetime, but works for datetime of today.

### ISSUE THREAD

**Issue by ghost** [benhoyt/graphyte#6]
Below are the things i tried to add to graphite.
Can anyone tell me where i am going wrong? The format is the same at the end.

#Does not work
val = datetime.strptime(strDatetime, '%m-%d-%Y %H:%M:%S').timestamp() + 0.1111111

#works
val = datetime.now().timestamp() + 0.0000011

**Comment by benhoyt** [comment]
Hmm, these both return a float for me, so I'm not sure why one would work and the other not. I don't think this is a bug in graphyte.

**Comment by benhoyt** [comment]
If you have a full program test case and can detail the errors you're seeing so others can reproduce it, that might be helpful.
